version: '3'

services:
  # app:
  #    network_mode: bridge
  #    build: .
  #    image: ${DOCKER_REG}${SERVICE_NAME}
  #    env_file: ./.env
  #    entrypoint: ./wait-for-it.sh eventide:5432 -s -t 45 -- npm
  #    container_name: ${SERVICE_NAME}
  #    ports:
  #      - ${PORT}:${PORT}
  #    depends_on:
  #      - eventide
  #    links:
  #      - eventide

  eventide:
    image: jpopesculian/eventide-postgres 
    network_mode: bridge
    ports:
      - 5432:5432
    expose:
      - 5432
